= Arithmetic
:fn_commute: footnote:[https://en.wikipedia.org/wiki/Commutative_property]
:fn_neg: footnote:[https://en.wikipedia.org/wiki/Additive_inverse]
:fn_div: footnote:[https://en.wikipedia.org/wiki/Multiplicative_inverse]


WARNING: work in progress

// Unicode symbols:
//   https://unicode-table.com/en/sets/mathematical-signs/

.binary operations

,===
symbol, name of binary operation, commutative? {fn_commute}

+,addition, yes
×,multiplication, yes
,===

.unary inverses 

,===
symbol, name of binary operation, commutative? {fn_commute}, name of unary inverse 

−, substraction, no, negation {fn_neg}
÷, division, no, reciprocal {fn_div}
,===

Subtraction and divistion as binary operations aren't commutative,
  ie `a - b ≠ b - a` and `a ÷ b ≠ b ÷ a`.
That's why forward uses the unary operations (which are inverses);
so that we can't preserve the commutative property.

Why do we want to preserve the commutative property?
Because in stack-based languages,
one thing that often bothers me is having to manipulate the stack
so that things are in the right order.
By having preserving the commutative property,
we don't have to worry as much in what order things are on the stack.

[ditaa]
----

Using commutative binary operations：

+-----------+       +-----------+
| + | a | b |   ＝   | + | b | a |
+-----------+       +-----------+

+-----------+       +-----------+
| × | a | b |   ＝   | × | b | a |
+-----------+       +-----------+

Using non－commutative binary operations：

+-----------+       +-----------+      +------------------+
| − | a | b |   ≠   | − | b | a |  --> | - | swap | a | b |
+-----------+       +-----------+      +------------------+

+-----------+       +-----------+      +------------------+
| ÷ | a | b |   ≠   | ÷ | b | a |  --> | ÷ | swap | a | b |
+-----------+       +-----------+      +------------------+

Using unary inverses instead：

negation
+-------+        +---------------+
| − | a |  -+->  | + | b | - | a |      same as： b + -a ＝ b - a
+-------+   |    +---------------+
            |    +---------------+
            +->  | + | - | a | b |      same as： -a + b ＝ b - a
                 +---------------+

reciprocal
+-------+        +---------------+
| ÷ | a |  -+->  | × | b | ÷ | a |    same as： b × (1/a) ＝ b / a
+-------+   |    +---------------+
            |    +---------------+
            +->  | × | ÷ | a | b |    same as： (1/a) × b ＝ b / a
                 +---------------+

----

// Due to a limitation in ditaa:
// I had to use ＝ instead of = and 
// I had to use ： instead of :
// I had to use －	instead of - in non-commutative
// https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)

.Interesting property of inverses:

****

https://en.wikipedia.org/wiki/List_of_types_of_numbers

* negation "creates" the negative numbers from the Natural numbers ℕ {1,2,3,4,...}, while
* reciprocal "creates" fractions from the Natural numbers 

In other words, these two inverses break the closure property of addition and multiplication (respectively).
****
