= Knowledge base
:toc:
:toc-placement!:

This is an AsciiDoc document
  footnote:[https://powerman.name/doc/asciidoc]
  footnote:[https://asciidoc.org/userguide.html]
  footnote:[https://github.com/powerman/asciidoc-cheatsheet]
acting as a knowledge base, of the background research being done while developing <<README.adoc#,forward>>.

I'm using Wikipedia,
since it covers a wide range of topics,
and aligns with the FOSS spirit of being free (ie not behind a paywall) and libre (ie licensed link:https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License[CC BY-SA]).

TIP: If you know of any other source that is freely available, can be accessed by anyone,
and that would be useful as a knowledge source for this knowledge base,
then feel free to open up an link:https://github.com/Bruno-366/forward/issues[issue] on forward's GitHub repository.

toc::[]

[#big-design-up-front-wikipedia]
== Big Design Up Front - Wikipedia footnote:[https://en.wikipedia.org/wiki/Big_Design_Up_Front]

> argue that BDUF is poorly adaptable to changing requirements 

> the needs of the business evolve at a pace faster than large projects are completed in - making the Big Design outdated by the time the system is completed. 

> If the cost of planning is greater than the cost of fixing then time spent planning is wasted. 

> run-time fixes are vastly more costly than design fixes 

> Improving software with the benefit of user feedback is generally less expensive than trying to anticipate and document every aspect of a system with BDUF 

> in most projects there is a significant lack of comprehensive written (or even well known) requirements. So in BDUF a lot of assumptions are made that later prove to be false 

> much easier to fix a requirements bug in the requirements phase than to fix that same bug in the implementation phase 

[#analysis-paralysis-wikipedia]
== Analysis paralysis - Wikipedia footnote:[https://en.wikipedia.org/wiki/Analysis_paralysis]

> exceedingly long phases of project planning, requirements gathering, program design, and data modeling, which can create little or no extra value

> Analysis paralysis can also arise from extensive experience or expertise, which serves to increase the number of options and considerations that appear at every decision point.

[#waterfall-model-wikipedia]
== Waterfall model - Wikipedia footnote:[https://en.wikipedia.org/wiki/Waterfall_model#Model]

> However he also felt it had major flaws stemming from the fact that testing only happened at the end of the process, which he described as being "risky and invites failure".

> Time spent early in the software production cycle can reduce costs at later stages

> a problem found in the early stages (such as requirements specification) is cheaper to fix than the same bug found later on in the process (by a factor of 50 to 200)

> emphasis on documentation

> new team members or even entirely new teams should be able to familiarise themselves by reading the documents

> In less thoroughly designed and documented methodologies, knowledge is lost if team members leave before the project is completed

> the model itself progresses linearly through discrete, easily understandable and explainable phases and thus is easy to understand

> Royce also advocated large quantities of documentation, doing the job "twice if possible"

> Designers may not be aware of future difficulties

> better to revise the design than persist in a design that does not account for any newly discovered constraints, requirements, or problems

[#incremental-build-model-wikipedia]
== Incremental build model - Wikipedia footnote:[https://en.wikipedia.org/wiki/Incremental_build_model]

> product is designed, implemented and tested incrementally (a little more is added each time) until the product is finished

> The product is decomposed into a number of components, each of which is designed and built separately

> allows partial utilization of the product and avoids a long development time

> System is broken down into many mini development projects.
  Partial systems are built to produce the final system.
  First tackled highest priority requirements.

> As additional functionality is added to the product, problems may arise related to system architecture which were not evident in earlier prototypes

> termed as builds). Each component is delivered to the client when it is complete

> The incremental model applies the waterfall model incrementally

[#cleanroom-software-engineering-wikipedia]
== Cleanroom software engineering - Wikipedia footnote:[https://en.wikipedia.org/wiki/Cleanroom_software_engineering]

> intended to produce software with a certifiable level of reliability

> defect prevention, rather than defect removal

> Software development based on formal methods

> Verification that the design correctly implements the specification is performed through team review, often with software tool support

[#formal-methods-wikipedia]
== Formal methods - Wikipedia footnote:[https://en.wikipedia.org/wiki/Formal_methods]

> Specification

> description of the system to be developed

> formalising system requirements

> Development

> If the formal specification is in axiomatic semantics, the preconditions and postconditions of the specification may become assertions in the executable code

> Verification

> prove that a formal model of a system implementation satisfies its specification

> Human-directed proof

> a desire to understand the system better

> Automated proof

> Critics note that some of those systems are like oracles: they make a pronouncement of truth, yet give no explanation of that truth. There is also the problem of "verifying the verifier";

> For sequential software, examples of formal methods include the B-Method, the specification languages used in automated theorem proving, RAISE, and the Z notation.

> In functional programming, property-based testing has allowed the mathematical specification and testing (if not exhaustive testing) of the expected behaviour of individual functions.

> For concurrent software and systems, Petri nets, process algebra, and finite state machines

> SPARK Ada

> TLA+

[#formal-specification-wikipedia]
== Formal specification - Wikipedia footnote:[https://en.wikipedia.org/wiki/Formal_specification]

> formal specifications are mathematically based

> describe a system

> formal in the sense that they have a syntax, their semantics fall within one domain

> Given such a specification, it is possible to use formal verification techniques to demonstrate that a system design is correct with respect to its specification

> This allows incorrect system designs to be revised before any major investments have been made into an actual implementation

> Formal specifications describe what a system should do, not how the system should do it.

> good specification must have some of the following attributes: adequate, internally consistent, unambiguous, complete, satisfied, minimal

> A design (or implementation) cannot ever be declared “correct” on its own. It can only ever be “correct with respect to a given specification”. Whether the formal specification correctly describes the problem to be solved is a separate issue

> Implementations of formal specifications will differ depending on what kind of system they are attempting to model

> State-based specification[3]
  behavior based on system states
  series of sequential steps, (e.g. a financial transaction)
  languages such as Z, VDM or B rely on this paradigm

> Transition-based specification[3]
  behavior based on transitions from state-to-state of the system
  best used with a reactive system

> Functional specification[3]
  specify a system as a structure of mathematical functions
  OBJ, ASL, PLUSS, LARCH, HOL or PVS rely on this paradigm

[#formal-verification-wikipedia]
== Formal verification - Wikipedia footnote:[https://en.wikipedia.org/wiki/Formal_verification]

> formal verification is the act of proving or disproving the correctness of intended algorithms underlying a system with respect to a certain formal specification

> Examples of mathematical objects often used to model systems are: finite state machines

> One approach and formation is model checking, which consists of a systematically exhaustive exploration of the mathematical model

> this is possible for finite models

> exploring all states

> Another approach is deductive verification

> It consists of generating from the system and its specifications (and possibly other annotations) a collection of mathematical proof obligations

> proof assistants (interactive theorem provers) (such as HOL, ACL2, Isabelle, Coq or PVS)

> requires the user to understand in detail why the system works correctly

> A promising type-based verification approach is dependently typed programming

> techniques can be sound, meaning that the verified properties can be logically deduced from the semantics, or unsound, meaning that there is no such guarantee

> A sound technique yields a result only once it has searched the entire space of possibilities

> An example of an unsound technique is one that searches only a subset of the possibilities, for instance only integers up to a certain number, and give a "good-enough" result

> Techniques can also be decidable, meaning that their algorithmic implementations are guaranteed to terminate with an answer, or undecidable, meaning that they may never terminate

> Verification: "Have we made what we were trying to make?", i.e., does the product conform to the specifications?

> Validation: "Are we trying to make the right thing?", i.e., is the product specified to the user's actual needs?

> use in the software industry is still languishing

[#group-like-structures-wikipedia]
== Group-like structures - Wikipedia footnote:[https://en.wikipedia.org/wiki/Template:Group-like_structures]

.Group-like structures
[format="csv"]
|====================================================================================
            ,       Totality,	Associativity,	Identity,	Invertibility,	Commutativity
Semigroupoid,       Unneeded,	Required,	      Unneeded,	Unneeded,     	Unneeded
Small Category,	    Unneeded,	Required,	      Required,	Unneeded,     	Unneeded
Groupoid,     	    Unneeded,	Required,     	Required,	Required,     	Unneeded
Magma,        	    Required,	Unneeded,     	Unneeded,	Unneeded,     	Unneeded
Quasigroup,   	    Required,	Unneeded,     	Unneeded,	Required,     	Unneeded
Unital Magma, 	    Required,	Unneeded,     	Required,	Unneeded,     	Unneeded
Loop,         	    Required,	Unneeded,     	Required,	Required,     	Unneeded
Semigroup,    	    Required,	Required,     	Unneeded,	Unneeded,     	Unneeded
Inverse Semigroup,	Required,	Required,     	Unneeded,	Required,     	Unneeded
Monoid,           	Required,	Required,     	Required,	Unneeded,     	Unneeded
Commutative monoid,	Required,	Required,     	Required,	Unneeded,     	Required
Group,            	Required,	Required,     	Required,	Required,     	Unneeded
Abelian group,    	Required,	Required,     	Required,	Required,     	Required
|====================================================================================
