:subtitle: Production Rules
:docinfo: shared
:relfileprefix: ../
include::{relfileprefix}README.adoc[tag=preamble]

:relfileprefix:

== {subtitle}

I would actually argue that the definition from Wikipedia isn't complete.
  footnote:[https://en.wikipedia.org/wiki/Formal_grammar]
(ğ, ğšº, ğ, ğ’) is just the data,
 â†’ is the operator over that data. 
Just as the natural numbers alone don't do much,
 but addition over the natural numbers,
 all of the sudden has much more meaning/use. 

.Integers under Addition
[example]
====
The set of integers under addition (Z,+) forms an abelian group,
 that has the property of closure, associativity and commutativity;
 as well as having an identity element and inverse element.
====

Additionally in this notation:

----
S â†’ aaB            <1> <2>
S â†’ abc            <2>
B â†’ c
----

<1> concatenation is implicit (by the juxtaposition of terminals/non-terminals), and
<2> alternation is sort of explicit (by defining another production rule with the same non-terminal on the LHS).

In BNF alternation is explicit (with `|`), while in EBNF both alternation and concatenation is explicit (with `|` and `,`).

.Alternation and Ambiguity
[NOTE]
====
The problem with alternation is that it makes the grammar ambiguous:
 if I have two production rule with the same non-terminal on the LHS,
 which one should I take?
Parsing expression grammar solve this by using ordered choice, ie pick the first matching choice.
====

I would argue that there is yet another operator missing and that is the expansion of non-terminals on the RHS of a production rule.

   P â‡’ Q ?

---

Thinking about it further;
 â†’ probably isn't an opertor,
 rather it is an relation.
Compare it to the equivalence relation `=` (ie, "equals") in normal algebra:

.Equals in normal algebra
[example]
----
y = 1 + x    â‡’ 6
x = 2 + 3    â‡’ 5
----

.Production rule in formal grammars
[example]
----
S â†’ aA   â‡’ abc
A â†’ bc   â‡’ bc
----

Luckily for us,
 just because a symbol is a relation rather than an operator,
 doesn't mean it doesn't have any properties.

For equality:
 footnote:[https://en.wikipedia.org/wiki/Equality_(mathematics)#Basic_properties]
 
* Substitution property: For any quantities a and b and any expression F(x), if a = b, then F(a) = F(b) (provided that both sides are well-formed).
** Some specific examples of this are:
** For any real numbers a, b, and c, if a = b, then a + c = b + c (here, F(x) is x + c);
** For any real numbers a, b, and c, if a = b, then a âˆ’ c = b âˆ’ c (here, F(x) is x âˆ’ c);
** For any real numbers a, b, and c, if a = b, then ac = bc (here, F(x) is xc);
** For any real numbers a, b, and c, if a = b and c is not zero, then a/c = b/c (here, F(x) is x/c).
* Reflexive property: For any quantity a, a = a.
* Symmetric property: For any quantities a and b, if a = b, then b = a.
* Transitive property: For any quantities a, b, and c, if a = b and b = c, then a = c.

In a type-0 grammar:
 footnote:[https://en.wikipedia.org/wiki/Chomsky_hierarchy#The_hierarchy]

* `a â†’ a` or `S â†’ S` might be valid, which is the Reflexive property.
* `S â†’ a` and `a â†’ S` might be valid, which is the Symmetric property.
* `S â†’ a` and `a â†’ B` and `B â†’ c` then `S â†’ c` might be valid, which is the Transitive property.
** `S â†’ B` and `B â†’ a` then `S â†’ a`. This is valid even in type-3 grammars (regular grammars)

