:subtitle: Composing grammars
:docinfo: shared
:relfileprefix: ../
include::{relfileprefix}README.adoc[tag=preamble]

:relfileprefix:

== {subtitle}

I would actually argue that the definition from Wikipedia isn't complete.
(ğ, ğšº, ğ, ğ’) is just the data,
 â†’ is the operator over that data. 
Just as the natural numbers alone don't do much,
 but addition over the natural numbers,
 all of the sudden has much more meaning/use. 

.Integers under Addition
[example]
====
The set of integers under addition (Z,+) forms an abelian group,
 that has the property of closure, associativity and commutativity;
 as well as having an identity element and inverse element.
====

Additionally in the above notation,
 concatenation is implicit (by the juxtaposition of terminals/non-terminals)
 and alternation is sort of explicit (by defining another production rule with the same non-terminal on the LHS).

.Alternation and Ambiguity
[NOTE]
====
The problem with alternation is that it makes the grammar ambiguous:
 if I have two production rule with the same non-terminal on the LHS,
 which one should I take?
Parsing expression grammar solve this by using ordered choice, ie pick the first matching choice.
====

In BNF alternation is explicit (with `|`), while in EBNF both alternation and concatenation is explicit (with `|` and `,`).

I would argue that there is yet another operator missing and that is the expansion of non-terminals on the RHS of a production rule.
