:subtitle: Arity
:docinfo: shared
:relfileprefix: ../
:dir: blog/
include::{relfileprefix}README.adoc[tag=preamble]

:relfileprefix:

== {subtitle}

=== Signature (logic) - Wikipedia footnote:[<https://en.wikipedia.org/wiki/Signature_(logic)>]

:hardbreaks:
> Formally, a (single-sorted) signature can be defined as a triple σ = (S~func~, S~rel~, ar)
> S~func~ and S~rel~ are disjoint sets, while ar is a function
>
> * function symbols (examples: +, ×, 0, 1)
> * relation symbols or predicates (examples: ≤, ∈)
> * a function ar: S~func~ ∪ S~rel~ → ℕ which assigns a natural number called arity to every function or relation symbol
>
> A signature with no function symbols is called a relational signature
> A signature with no relation symbols is called an algebraic signature

:hardbreaks!:

=== Defining arity

[source,math]
----
f(x) = x + 5          <1>
g(x,y) = x + y        <2>
h(x1,x2,...xn) = ∑ xn <3>
----

<1> function f of arity 1, adds five to its 1 input
<2> function g of arity 2, returns the sum of its 2 two input numbers
<3> function h of arity n, returns the sum of several numbers

In a stack-based language:

[source,forth]
----
: add  ( a b -- c ) + ;           <1>
: add5 ( a -- c ) 5 + ;           <2>
: sum ( array -- c ) [ + ] reduce ;  <3>
----

<1> word `add`  of arity 2, takes as input 2 numbers, returns the sum of those numbers
<2> word `add5` of arity 1, takes as input 1 number, adds five to its 1 input
<2> word `sum`  of arity 1, takes as input 1 array, returns the sum of the numbers contained in the array



curried functions:
