:subtitle: Name vs Property Checking
:docinfo: shared
:relfileprefix: ../
:dir: blog/
include::{relfileprefix}README.adoc[tag=preamble]

:relfileprefix:

== {subtitle}

There are some terms related to what I'm about to discuss that don't quite capture the orthogonality that I'm trying to portray here.
Statuc vs dynamic typing, duck typing, dependent types, property checking.

> I'm going to demonstrate these concepts using executable factor code,
so you that can run them yourself and experiment with them 

=== Number checking
Number checking is the simplest form of type checking, I could think of.
We just check that the number of argments on the stack match.
However, first I need to introduce some concepts to make this discussion easier.

primitive:: a piece of executablt code that is in-built,
and whose correct implementation is something the rest of the code-base assumes & depends on.

phrase:: a piece of executablt code that is built from primitives.
We have to tell the computer how we expect our written code to behave.

named phrase:: a phrase that we give a name to, so that we may use it again.
This is equivalent to assigning an anonymous function to a variable in other programming languages. 

anonymous phrase:: a phrase that isn't given a name.

word:: a phrase or a primitive

.primitives
In the example below, `five`, `add`, `number2string`, and `print` are primitives.
We expect them to be already implemented, but more importantly,
we expect their type annotations to be correct.
So if `add` says it takes `2` inputs and outputs `1` thing,
I am going to trust it and not concern myself with how that is so.

.phrase
In the example below, `add5print` is a phrase.
We are telling the computer that we expect it to take as input `1` thing and output `0` things.

```factor
: type:five                 [ 0 ] [ 1 ] ; ! <2>
: type:add                  [ 2 ] [ 1 ] ; ! <1> <2>
: type:number2string        [ 1 ] [ 1 ] ; ! <1>
: type:print                [ 1 ] [ 0 ] ; ! <1>

:primitve add + ;
:primitve five 5 ;
:primitve print . ;

: type:add5print            [ 1 ] [ 0 ] ;
:phrase add5print five add number2string print ;
```

==== Number checking: two words

There are three cases to consider in this example.

:hardbreaks:
. The stacks effects of two words match up.
  For example: `add` outputs a `1` thing,
  and `number2string` takes as input a `1` thing.
  This is great!
. There is a stack under-supply.  
  For example: `five` just outputs `1` thing,
  while `add` takes as input `2` things.
  If we ran `five add` we would get a stack under-supply (`1 != 2`).
  This is an error.
. There is a stack over-supply.
  For example: `number2string` takes as input `1` thing,
  while `five five` outputs `2` things (the number 5 twice).
  This is not a problem, since what isn't used up remains on the stack for the next word. (`2 == 1`)

==== Number checking: anonymous phrases


==== Number checking: named phrases



=== Name checking

Name checking is the simplest form of type checking, I could think of.

.primitives
In the example below, `five`, `add`, `number2string`, and `print` are primitives.
We expect them to be already implemented, but more importantly,
we expect their type annotations to be correct.
So if `number2string` says it has a type effect of `Number -- String`,
I am going to trust it and not concern myself with how that is so.

.phrase

.type stack
There are five cases to consider in this example.

:hardbreaks:
. The stacks effects of two words match up.
  For example: `add` outputs a `Number`,
  and `number2string` takes as input a `Number`
. There is a stack under-supply.  
  For example: `add` takes as input two `Number`​s,
  while `five` just outputs one `Number`.
  If we ran `five add` we would get a stack under-supply (`Number != Number Number`).
  If we ran instead `five five add` then things would match up (`Number Number == Number Number`) 
. There is a stack over-supply.
  For example: `number2string` takes as input one `Number`,
  while `five five` outputs two `Number`​s (the number 5 twice).
  This is not a problem, since what isn't used up remains on the stack for the next word. (`Number`, `Number == Number`)
. Type checking a phrase
  `add5print` has the type annotation `[ Number ] [ ]`,
  to check whether or not this annotation is correct,
  we will take the type annotations of all the words contained whithin `add5print`,
  ie `five add number2string print`:
  `[ ] [ Number ] [ Number Number ] [ Number ] [ Number ] [ String ] [ String ] [ ]`.
  Then we will insert that in-between `add5print` own type annotation `[ Number ] [ ]`:
  `[ Number ] [ ] [ Number ] [ Number Number ] [ Number ] [ Number ] [ String ] [ String ] [ ] [ ]`.

:!hardbreaks:


[draw]
----
IF type-stack A == type-stack B
THEN drop

five add
type-stack A       type-stack B       result:
Number        =    Number                    
                   Number             Number

five five add
type-stack A       type-stack B       result:
Number        =    Number                    
Number        =    Number                    
----

```factor

: type:five                 [ ] [ Number ] ; ! <2>
: type:add    [ Number Number ] [ Number ] ; ! <1> <2>
: type:number2string [ Number ] [ String ] ; ! <1>
: type:print         [ String ] [ ] ;        ! <1>

:primitve add + ;
:primitve five 5 ;
:primitve print . ;

: type:add5print      [ Number ] [ ] ;
:phrase add5print five add number2string print ;
```
:hardbreaks:

<1> `add number2string print` results in the type stack the following values:
    `[ Number Number ] [ Number ] [ Number ] [ String ] [ String ] [ ]`
    You'll see that `Number = Number` and `String = String`
    
<2> then there are the cases when the type stack doesn't match up exactly.
    if we execute `add` on an empty stack we will get a stack underflow, because
    it expects two numbers and we have given it nothing.

:!hardbreaks:


=== Property checking
```factor
( isNumber? isNumber? -- isNumber? )
: add + ;
```

=== dependent Property checking
```factor
( isNumber? isNumber? -- isNumber? )
: add + ;
```

dependent, because it actually depends on the arguments
