:subtitle: Composing grammars
:relfileprefix: ../
include::../README.adoc[tag=preamble]

:relfileprefix:

== {subtitle}

Parsers can be composed using parser combinators,
  footnote:[https://en.wikipedia.org/wiki/Parser_combinator]
but what about the grammars themselves?
How does that work?

=== From Wikipedia:

In the classic formalization of generative grammars first proposed by Noam Chomsky in the 1950s, a grammar ğ† consists of the following components:
  footnote:[https://en.wikipedia.org/wiki/Formal_grammar#The_syntax_of_grammars]

* A finite set ğ of nonterminal symbols, that is disjoint with the strings formed from ğ’.
* A finite set ğšº of terminal symbols that is disjoint from ğ.
* A finite set ğ of production rules, each rule of the form (ğšº âˆª ğ)^\*^ğ(ğšº âˆª ğ)^\*^ -> (ğšº âˆª ğ)^\*^
where ^\*^ is the Kleene star operator and âˆª denotes set union. 
* A distinguished symbol ğ’ âˆˆ ğ that is the start symbol, also called the sentence symbol.

A grammar is formally defined as the tuple (ğ, ğšº, ğ, ğ’). 

---

=== Composing regular grammars

The first grammar ğ†: (ğ, ğšº, ğ, ğ’). 

* A finite set ğ = { ğ’ }.
* A finite set ğšº  = { a }.
* A finite set ğ of production rules, each rule of the form ğ -> (ğšº âˆª ğ)^\*^
footnote:[regular gammars have restrictions on the production rules]

This grammar defines the language L(ğ†) = { a^n^ | n = 1 } where a^n^ denotes a string of n consecutive a's.

The second grammar ğ†': (ğ', ğšº', ğ', ğ’'). 

* A finite set ğ' = { ğ’' }.
* A finite set ğšº'  = { b }.
* A finite set ğ' of production rules, each rule of the form ğ -> (ğšº âˆª ğ)^\*^

This grammar defines the language L(ğ†') = { b^n^ | n = 1 }.


Composing the two grammars:

ğ† + ğ†': (ğ âˆª ğ', ğšº âˆª ğšº', ğ âˆª ğ', ???)

Since ğ, ğšº, and ğ are finite sets, the easiest thing to do is a union of the two grammars.
However ğ’, the start symbol, is supposed to be unique in the ğ set, ie there is only one starting point for a grammar.
That is at least a common underlying assumption.
So what do we do when we are trying to compose grammars, and end up with several starting symbols?

Since ğ’ is a nonterminal ğ, we can think in more abstract terms: what do we do when we have several nonterminals?
Well, we can concatenate them, or alternate them. 

footnote:[https://en.wikipedia.org/wiki/Formal_language#Operations_on_languages]


+++
<script src="https://utteranc.es/client.js"
        repo="bruno-366/forward"
        issue-term="pathname"
        label="Comment"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
+++
