:subtitle: Grammar subsets
:docinfo: shared
:relfileprefix: ../
include::{relfileprefix}README.adoc[tag=preamble]

:relfileprefix:

== {subtitle}

toc::[]

=== Tokenizer vs Parser

consider a more <<general>> grammar allowing all words

[source,yacc]
----
<char>  ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
<chars> ::= <char> <chars> | <char>
<word>  ::= <chars> " "
<words> ::= <word> <words> | <word>
----

or, a more <<specific>> grammar, defining the exactly the words we are going to use

[source,yacc]
----
<word> ::= "hello" | "world" | "bye"
<sentence> ::= <word> "." | <word> " " <sentence>
----

bnfplayground:
[bibliography]
* [[[general]]] https://bnfplayground.pauliankline.com/?bnf=%3Cchar%3E%20%3A%3A%3D%20%22a%22%20%7C%20%22b%22%20%7C%20%22c%22%20%7C%20%22d%22%20%7C%20%22e%22%20%7C%20%22f%22%20%7C%20%22g%22%20%7C%20%22h%22%20%7C%20%22i%22%20%7C%20%22j%22%20%7C%20%22k%22%20%7C%20%22l%22%20%7C%20%22m%22%20%7C%20%22n%22%20%7C%20%22o%22%20%7C%20%22p%22%20%7C%20%22q%22%20%7C%20%22r%22%20%7C%20%22s%22%20%7C%20%22t%22%20%7C%20%22u%22%20%7C%20%22v%22%20%7C%20%22w%22%20%7C%20%22x%22%20%7C%20%22y%22%20%7C%20%22z%22%0A%3Cword%3E%20%3A%3A%3D%20%3Cchars%3E%20%22%20%22%0A%3Cchars%3E%20%3A%3A%3D%20%3Cchar%3E%20%3Cchars%3E%20%7C%20%3Cchar%3E%0A%3Cwords%3E%20%3A%3A%3D%20%3Cword%3E%20%3Cwords%3E%20%7C%20%3Cword%3E%0A&name=[link]
* [[[specific]]] https://bnfplayground.pauliankline.com/?bnf=%3Cword%3E%20%3A%3A%3D%20%22hello%22%20%7C%20%22world%22%20%7C%20%22bye%22%0A%3Csentence%3E%20%3A%3A%3D%20%3Cword%3E%20%22.%22%20%7C%20%3Cword%3E%20%22%20%22%20%3Csentence%3E%0A&name=[link]

=== Subsets

We know that the more specific grammar is NOT a subset of the more general grammar,
  due to the punctuation mark.

However, it would be cool to be able to reason about grammars in such a way.
In other words, if we removed the period (`<sentence> ::= <word> | <word> " " <sentence>`),
  could we prove that the specifc grammar is a subset of the more general grammar?

Let's give a try:

A grammar is <<composing-grammars.adoc#from-wikipedia,formally defined>> as the tuple (𝐍, 𝚺, 𝐏, 𝐒).
𝐍 is non-terminals, 𝚺 is terminals, 𝐏 is production rules, 𝐒 is the starting symbol.
Well, right of the bat, we can see the production rules in their current formulation are disjoint,
  ie the grammars don't have any production rules in common.
The terminals are also disjoint, although one could make the case that
  (after removing the punctuation mark) the terminals of the specific grammar
  are made up of the terminals of the general grammar.
Let's try that, by changing the notational a bit:

==== Subsets of terminals

The general grammar:

----
CHAR -> a
CHAR -> b
CHAR -> c
CHAR -> d
CHAR -> e
CHAR -> f
CHAR -> g
CHAR -> h
CHAR -> i
CHAR -> j
CHAR -> k
CHAR -> l
CHAR -> m
CHAR -> n
CHAR -> o
CHAR -> p
CHAR -> q
CHAR -> r
CHAR -> s
CHAR -> t
CHAR -> u
CHAR -> v
CHAR -> w
CHAR -> x
CHAR -> y
CHAR -> z
CHARS -> CHAR
CHARS -> CHAR CHARS
WORD -> CHARS " "
WORDS -> WORD
WORDS -> WORD WORDS
----

Our terminals for the general grammar are clearly all of the lowercase letters of the english alphabet, plus space.

  𝚺 = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, " " }

The specific grammar:

----
WORD -> h e l l o
WORD -> w o r l d
WORD -> b y e
SENTENCE -> WORD
SENTENCE -> WORD " " SENTENCE
----

Our terminals for the specific grammar are the following lowercase letters, plus space:

  𝚺' = { b, d, e, h, l, o, r, w, y, " " }
  
So clearly: 𝚺' ⊊ 𝚺
(the terminals of the specific grammar are a subset of the general grammar's) 
  
==== Subsets of non-terminals

If we rename the non-terminals rules of the specific grammar,
  so that they match those of the general grammar:

----
WORD -> h e l l o
WORD -> w o r l d
WORD -> b y e
WORDS -> WORD
WORDS -> WORD " " WORDS
----

So, we had `𝐍' = { WORD, SENTENCE }`.
Now, we have:

  𝐍' = { WORD, WORDS }

And for the general grammar:

  𝐍 = { CHAR, CHARS, WORD, WORDS }

So clearly: 𝐍' ⊊ 𝐍
(the non-terminals of the specific grammar are a subset of the general grammar's) 

Here's the
  link:https://bnfplayground.pauliankline.com/?bnf=%3Cword%3E%20%3A%3A%3D%20%22hello%22%20%7C%20%22world%22%20%7C%20%22bye%22%0A%3Cwords%3E%20%3A%3A%3D%20%3Cword%3E%20%20%7C%20%3Cword%3E%20%22%20%22%20%3Cwords%3E%0A&name=[link]
to the specifc grammar, without the punctuation marks, and the renamed non-terminals.

==== Subsets of production rules
