= Programming Paradigms: and their constructs 
:toc:
:source-highlighter: pygments
:icons: font

The three main programming paradigms in widespread use today are:

. Imperative
. Functional
. Object oriented 

Each paradigm has different a different approach to how they solve problems.

.Here's a summary of the main concepts related to each paradigm:

1. Imperative: 
    * if else then
    * while, do until, for loops
2. Functional
    * map, filter, reduce
    * curry, partial application 
3. Object oriented 

We are also going to implement these constructs from scratch

* if else then: short circuit
* loops: goto or recursion
* map, filter, reduce: recursion
* curry, partial application


****
We are going to present these constructs in javascript, bash and lua.
I recommend checking out the following resources;

* javascript:
  https://learnxinyminutes.com/docs/javascript/[cheatsheet] for a 5-10 minute introduction or memory aide.
  https://replit.com/languages/javascript[online] interpreter, to run javascript code.
* bash:
  https://learnxinyminutes.com/docs/bash/[cheatsheet] for a 5-10 minute introduction or memory aide.
  https://replit.com/languages/bash[online] interpreter, to run bash code.
* lua:
  https://learnxinyminutes.com/docs/lua/[cheatsheet] for a 5-10 minute introduction or memory aide.
  https://replit.com/languages/lua[online] interpreter, to run lua code.
  
The cheatsheets are going to cover stuff that are more specific to each language.
We, on the other hand, are going to use the languages to highlight concepts.
These concepts are common among several programming languages, not just the ones mentioned here.

****

== Basics: functions and variables

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=function,indent=0]
include::others-mainstream.js[tag=anonFunction,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=function,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=function,indent=0]
----

== Imperative constructs

=== if else then

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=ifElse,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=ifElse,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=ifElse,indent=0]
----

=== while, do until, for loops

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=loops,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=loops,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=loops,indent=0]
----

== Imperative constructs from scratch 

=== if else then: short circuit

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=short,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=short,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=short,indent=0]
----

=== loops: goto or recursion

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=recursion,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=recursion,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=recursion,indent=0]
----

== Functional constructs

=== map, filter, reduce

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=mapReduce,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=mapReduce,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=mapReduce,indent=0]
----
    
=== curry, partial application 

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=partial,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=partial,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=partial,indent=0]
----

== Functional constructs from scratch 


== Object-Oriented constructs

== Object-Oriented constructs from scratch 



= Present programming languages: and their applications

1. Imperative: 
    * C
2. Functional
    * JavaScript 
3. Object oriented 
    * JavaScript 
