= Programming Paradigms: and their constructs 
:toc:
:source-highlighter: pygments
:icons: font
:stem:

The three main programming paradigms in widespread use today are:

. Imperative programming
. Functional programming
. Object-oriented programming

Each paradigm has different a different approach to how they solve problems.
We are going to go over some concepts that are central to each paradigm.
We are also going to implement these constructs from scratch.
We are just looking at the semantics of the programming languages.
Other aspects of software developement aren't going to be covered here.
This includes aspects such as agile vs waterfall vs scrum, or dynamic typing vs static typing.

****
.semantics vs syntax

I have tried to minimize any syntactical differences between the languages.
This way, we can focus on the semantical differences between the languages.

But, what does syntax and semantics mean?
A quick explaination is that the semantics of a language is the underlying meaning of a language.
For example, in these all have similar semantics:

English greeting:: "hello"
Spanish greeting:: "hola"
French greeting:: "bonjour"
Chinese greeting:: "你好"

****

We are going to present these constructs in `javascript`, `bash` and `lua`.
I recommend checking out the following resources;

* `javascript`:
  https://learnxinyminutes.com/docs/javascript/[cheatsheet] for a 5-10 minute introduction or memory aide.
  https://replit.com/languages/javascript[online] interpreter, to run javascript code.
* `bash`:
  https://learnxinyminutes.com/docs/bash/[cheatsheet] for a 5-10 minute introduction or memory aide.
  https://replit.com/languages/bash[online] interpreter, to run bash code.
* `lua`:
  https://learnxinyminutes.com/docs/lua/[cheatsheet] for a 5-10 minute introduction or memory aide.
  https://replit.com/languages/lua[online] interpreter, to run lua code.
  
The cheatsheets are going to cover stuff that are more specific to each language.
We, on the other hand, are going to use the languages to highlight concepts.
These concepts are common among several programming languages, not just the ones mentioned here.

== Basics: functions and variables

The most fundemental feature in by far the vast majority of programming languages is functions.
Functions take inputs and output something in return.
You probably recognize this from maths.

[math]
++++
f(x) = sqrt(1+x^2)
++++

In the above example, we assume that both the inputs and outputs are numbers.
In programming we regularly work with a far more diverse range of "things".
Here's an example:

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=function,indent=0]
include::others-mainstream.js[tag=anonFunction,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=function,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=function,indent=0]
----

These functions take as input some text, and return the boolean value `True`.
Boolean variables can only have one of two values: `True` or `False`.

== Imperative constructs

=== if else then

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=ifElse,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=ifElse,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=ifElse,indent=0]
----

=== while, do until, for loops

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=loops,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=loops,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=loops,indent=0]
----

== Imperative constructs from scratch 

=== if else then: short circuit

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=short,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=short,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=short,indent=0]
----

=== loops: goto or recursion

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=recursion,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=recursion,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=recursion,indent=0]
----

== Functional constructs

=== map, filter, reduce

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=mapReduce,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=mapReduce,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=mapReduce,indent=0]
----
    
=== curry, partial application 

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=partial,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=partial,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=partial,indent=0]
----

== Functional constructs from scratch 

=== map, reduce, filter: recursion

=== partial application: pattern-matching or currying 


== Object-Oriented constructs

=== properties and methods

=== inheritance

== Object-Oriented constructs from scratch 

=== properties and methods: dictionaries


= Present programming languages: and their applications

1. Imperative: 
    * C
2. Functional
    * JavaScript 
3. Object oriented 
    * JavaScript 
