= Programming Paradigms: and their constructs 
:toc:
:source-highlighter: pygments
:icons: font

The three main programming paradigms in widespread use today are:

. Imperative
. Functional
. Object oriented 

Each paradigm has different a different approach to how they solve problems.

.Here's a summary of the main concepts related to each paradigm:

1. Imperative: 
    * if else then
    * while, do until, for loops
2. Functional
    * map, filter, reduce
    * curry, partial application 
3. Object oriented 

We are also going to implement these constructs from scratch

* if else then: short circuit
* loops: goto or recursion
* map, filter, reduce: recursion
* curry, partial application


****
we are going to present these constructs in bash and javascript.

* https://learnxinyminutes.com/docs/javascript/
* https://learnxinyminutes.com/docs/bash/
* https://learnxinyminutes.com/docs/lua/
* https://replit.com/languages/bash
* https://replit.com/languages/javascript
* https://replit.com/languages/lua

****

== Imperative constructs

=== if else then

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=ifElse,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=ifElse,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=ifElse,indent=0]
----

=== while, do until, for loops

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=loops,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=loops,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=loops,indent=0]
----

== Imperative constructs from scratch 

=== if else then: short circuit

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=short,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=short,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=short,indent=0]
----

=== loops: goto or recursion

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=recursion,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=recursion,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=recursion,indent=0]
----

== Functional constructs

=== map, filter, reduce

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=mapReduce,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=mapReduce,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=mapReduce,indent=0]
----
    
=== curry, partial application 

[source,javascript]
----
// javascript
include::others-mainstream.js[tag=partial,indent=0]
----

[source,shell]
----
# bash
include::others-mainstream.sh[tag=partial,indent=0]
----

[source,lua]
----
-- lua
include::others-mainstream.lua[tag=partial,indent=0]
----

== Functional constructs from scratch 


== Object-Oriented constructs

== Object-Oriented constructs from scratch 



= Present programming languages: and their applications

1. Imperative: 
    * C
2. Functional
    * JavaScript 
3. Object oriented 
    * JavaScript 
